### ISSUE TITLE
ERROR: Compiling summary protocol buffers failed

### ISSUE THREAD

**Issue by jacky4323** [awslabs/mxboard#19]
Hi,

When I run python setup.py install,it show some errors
![image](https://user-images.githubusercontent.com/31586393/39081699-71607fc0-4578-11e8-9c14-a0507d7e6307.png)

but I already install protobuf3 by using pip install protobuf

![image](https://user-images.githubusercontent.com/31586393/39081719-d5df45ee-4578-11e8-8efb-face47b7bd8c.png)

**Comment by reminisce** [comment]
Seems you have installed protobuf2. Could you type
```bash
protoc --version
```
and paste the output here?

**Comment by jacky4323** [comment]
@reminisce 
protoc  --version
result shows the version libprotoc 2.6.1

**Comment by reminisce** [comment]
You installed protobuf2. You need to uninstall it and install version 3 either from PyPI or Anaconda.
https://pypi.org/project/protobuf/3.5.1/
https://anaconda.org/conda-forge/protobuf

**Comment by jacky4323** [comment]
thanks a lot !!
