### ISSUE TITLE
multiple scalar summaries in one plot

### ISSUE THREAD

**Issue by casscw** [awslabs/mxboard#20]
how to record multiple scalar summaries in one plot

**Comment by casscw** [comment]
thanks.

**Comment by reminisce** [comment]
Thanks for asking the question. I will keep this issue open until the request is fulfilled.

**Comment by reminisce** [comment]
https://github.com/awslabs/mxboard/pull/21 has enabled users to draw multiple curves in the same plot. Please see here for examples:
https://github.com/awslabs/mxboard/blob/master/demo.md#scalar

Feel free to let me know if you have more questions or requests. Thanks.

**Comment by casscw** [comment]
大佬666 回头试试
