### ISSUE TITLE
No handlers could be found for logger "mxboard.event_file_writer"

### ISSUE THREAD

**Issue by HarveyGuo960817** [awslabs/mxboard#30]
Hello, i install mxboard and run the demo py, but raise errors:

No handlers could be found for logger "mxboard.event_file_writer"

my conda list is as follows:
mxboard                   0.1.0                     <pip>
mxnet                     1.2.0                     <pip>
tensorboard               1.12.0                    <pip>
tensorflow                1.12.0

how can i solve this, thank u very much!

**Comment by eric-haibin-lin** [comment]
+1

**Comment by eric-haibin-lin** [comment]
Did you try python 3? It didn't work with py2 for me but py3 is ok

**Comment by reminisce** [comment]
Thanks for reporting the issue. It should now be fixed in the master branch. Can you checkout the latest code from the master branch and do `python2.7 setup.py install`?

**Comment by eric-haibin-lin** [comment]
works for me now

**Comment by reminisce** [comment]
Thanks for confirming. Closing the issue now.

**Comment by ryol8888** [comment]
+1

Python 2.7.16 :: Anaconda, Inc.
mxboard 0.1.0
mxnet 1.4

**Comment by Light--** [comment]
same problem here, how to solve it?
