### ISSUE TITLE
 Appending to event file

### ISSUE THREAD

**Issue by lambdaofgod** [awslabs/mxboard#38]
Is there a way to make SummaryWriter append to old event file, instead of creating new one each time it's called?

Or is there any other method to prepare log files, so that if I interrupt and then continue training later, get a desired Tensorboard output (and not just graph with duplicated values)?.

**Comment by reminisce** [comment]
I think it's possible. Just need to figure out the appropriate way of opening the existing event file and append content, but so far, it's not implemented.
