### ISSUE TITLE
[bug] SummarWriter.add_embedding with images=None fails

### ISSUE THREAD

**Issue by fhieber** [awslabs/mxboard#7]
`add_embedding()` is checking for `images is not None` but when adding the embedding config at the end of the functions it expects `images.shape` which fails if images=None.

**Comment by reminisce** [comment]
Thanks for reporting this. I have fixed the bug and refreshed the master branch and pip package on PyPI.
I have also added test coverage for various cases of `add_embedding`.

**Comment by reminisce** [comment]
Fixed by PR https://github.com/awslabs/mxboard/pull/8
